type: object
required:
  - name
  - description
  - schema_version
  - version
  - api_version
  - resources
properties:
  name:
    type: string
    maxLength: 255
  description:
    type: string
  schema_version:
    type: integer
    enum:
      - 1
  version:
    type: string
    minLength: 5
    maxLength: 64
  api_version:
    type: string
    enum:
      - v1
  requirements:
    type: object
  resources:
    type: object
    properties: {}
  exports:
    type: object
  imports:
    type: object
components:
  schemas: {}
