site_name: genesis_core
site_url: https://github.com/infraguys/
repo_name: genesis_core
repo_url: https://github.com/infraguys/genesis_core
edit_uri: browse/docs/

theme:
  name: material
  language: en
  features:
    - search.suggest
    - search.highlight
    # to move menu to top uncomment the following lines
    # - navigation.tabs
    # - navigation.tabs.sticky
    - toc.integrate
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Russian
          build: true
  - search:
      lang:
        - en
        - ru
  - glightbox
  - render_swagger

extra:
  repo_icon: github

markdown_extensions:
  - meta
  - admonition
  - footnotes
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: '#'
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Software: index.md
  - Usage: usage/basic_usage.md
  - OpenAPI:
    - Boot: openapi/openapi_boot.md
    - Orch: openapi/openapi_orch.md
    - Status: openapi/openapi_status.md
    - User: openapi/openapi_user.md
  - Element:
    - Manifest: em/manifest.md
    - Service as a Service API: em/service.md
    - Example commands: em/cli.md
  - IAM:
    - Permissions Overview: iam/permissions_overview.md
  - Network:
    - Load Balancer as a Service API: network/load_balancer.md
  - Secrets:
      - Certificates: secret/certificates.md