[DEFAULT]
verbose = True
debug = True

[universal_agent]
orch_endpoint = http://localhost:11011
status_endpoint = http://localhost:11011
caps_drivers = CoreCapabilityDriver


[CoreCapabilityDriver]
username = admin
password = admin
user_api_base_url = http://localhost:11010
